# Servidor y Base de Datos H2
spring.datasource.url=jdbc:h2:mem:oreodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JWT Secret
app.jwt.secret=${JWT_SECRET:ClaveSuperSecretaDeAlMenos32BytesDeLargo123456}

# GitHub Models API (Requerimientos de la Rúbrica)
github.models.token=${GITHUB_TOKEN:}
github.models.url=${GITHUB_MODELS_URL:https://models.inference.ai.azure.com/chat/completions}
github.models.model=${MODEL_ID:gpt-4o-mini}

# Configuración de Mail
spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true