spring.application.name=oreo-insight-factory
spring.datasource.url=jdbc:h2:mem:oreodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

app.jwt.secret=ClaveSuperSecretaDeAlMenos32BytesDeLargo123456
app.github.token=tu_token_aqui
app.github.models-url=https://models.inference.ai.azure.com/chat/completions
app.github.model-id=gpt-5-mini

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu_email@gmail.com
spring.mail.password=tu_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true